export interface Icon {
  name: string;
  class: string;
}

export const ICON_CATEGORIES: Record<string, Icon[]> = {
  "الخدمات العامة": [
    { name: "Palette", class: "fas fa-palette" },
    { name: "Code", class: "fas fa-code" },
    { name: "Bullhorn", class: "fas fa-bullhorn" },
    { name: "Pen Nib", class: "fas fa-pen-nib" },
    { name: "Briefcase", class: "fas fa-briefcase" },
    { name: "Gavel", class: "fas fa-gavel" },
    { name: "Cog", class: "fas fa-cog" },
    { name: "Cogs", class: "fas fa-cogs" },
    { name: "Wrench", class: "fas fa-wrench" },
    { name: "Shield Alt", class: "fas fa-shield-alt" },
    { name: "Life Ring", class: "far fa-life-ring" },
    { name: "Tools", class: "fas fa-tools" },
    { name: "Magic", class: "fas fa-magic" },
    { name: "Globe", class: "fas fa-globe" },
    { name: "Users Cog", class: "fas fa-users-cog" },
  ],
  "الأعمال والمكاتب": [
    { name: "Building", class: "far fa-building" },
    { name: "File Alt", class: "far fa-file-alt" },
    { name: "File Invoice Dollar", class: "fas fa-file-invoice-dollar" },
    { name: "File Signature", class: "fas fa-file-signature" },
    { name: "Chart Bar", class: "far fa-chart-bar" },
    { name: "Chart Line", class: "fas fa-chart-line" },
    { name: "Chart Pie", class: "fas fa-chart-pie" },
    { name: "Landmark", class: "fas fa-landmark" },
    { name: "Calculator", class: "fas fa-calculator" },
    { name: "Handshake", class: "far fa-handshake" },
    { name: "Lightbulb", class: "far fa-lightbulb" },
    { name: "Suitcase", class: "fas fa-suitcase" },
    { name: "Project Diagram", class: "fas fa-project-diagram" },
    { name: "Sitemap", class: "fas fa-sitemap" },
    { name: "Stamp", class: "fas fa-stamp" },
  ],
  "التواصل والشبكات": [
    { name: "Whatsapp", class: "fab fa-whatsapp" },
    { name: "Telegram", class: "fab fa-telegram-plane" },
    { name: "Facebook", class: "fab fa-facebook-f" },
    { name: "Twitter", class: "fab fa-twitter" },
    { name: "Instagram", class: "fab fa-instagram" },
    { name: "LinkedIn", class: "fab fa-linkedin-in" },
    { name: "Youtube", class: "fab fa-youtube" },
    { name: "Envelope", class: "far fa-envelope" },
    { name: "Phone", class: "fas fa-phone" },
    { name: "Comments", class: "far fa-comments" },
    { name: "Comment Dots", class: "far fa-comment-dots" },
    { name: "Share Square", class: "far fa-share-square" },
    { name: "At", class: "fas fa-at" },
    { name: "Broadcast Tower", class: "fas fa-broadcast-tower" },
    { name: "Rss", class: "fas fa-rss" },
  ],
  "التصميم والإبداع": [
    { name: "Paint Brush", class: "fas fa-paint-brush" },
    { name: "Drafting Compass", class: "fas fa-drafting-compass" },
    { name: "Edit", class: "far fa-edit" },
    { name: "Crop Alt", class: "fas fa-crop-alt" },
    { name: "Vector Square", class: "fas fa-vector-square" },
    { name: "Fill Drip", class: "fas fa-fill-drip" },
    { name: "Swimmer", class: "fas fa-swimmer" },
    { name: "Layer Group", class: "fas fa-layer-group" },
    { name: "Object Group", class: "far fa-object-group" },
    { name: "Pen", class: "fas fa-pen" },
    { name: "Ruler Combined", class: "fas fa-ruler-combined" },
    { name: "Tshirt", class: "fas fa-tshirt" },
    { name: "Bezier Curve", class: "fas fa-bezier-curve" },
    { name: "Broom", class: "fas fa-broom" },
    { name: "Eraser", class: "fas fa-eraser" },
  ],
  "الوسائط المتعددة": [
    { name: "Image", class: "far fa-image" },
    { name: "Images", class: "far fa-images" },
    { name: "Video", class: "fas fa-video" },
    { name: "Film", class: "fas fa-film" },
    { name: "Music", class: "fas fa-music" },
    { name: "Headphones", class: "fas fa-headphones-alt" },
    { name: "Microphone", class: "fas fa-microphone" },
    { name: "Camera", class: "fas fa-camera" },
    { name: "Camera Retro", class: "fas fa-camera-retro" },
    { name: "Play Circle", class: "far fa-play-circle" },
    { name: "Podcast", class: "fas fa-podcast" },
    { name: "Photo Video", class: "fas fa-photo-video" },
    { name: "Sliders H", class: "fas fa-sliders-h" },
    { name: "Volume Up", class: "fas fa-volume-up" },
    { name: "Record Vinyl", class: "fas fa-record-vinyl" },
  ],
  "التجارة الإلكترونية": [
    { name: "Shopping Cart", class: "fas fa-shopping-cart" },
    { name: "Shopping Bag", class: "fas fa-shopping-bag" },
    { name: "Store", class: "fas fa-store" },
    { name: "Credit Card", class: "far fa-credit-card" },
    { name: "Tag", class: "fas fa-tag" },
    { name: "Tags", class: "fas fa-tags" },
    { name: "Barcode", class: "fas fa-barcode" },
    { name: "Qrcode", class: "fas fa-qrcode" },
    { name: "Gift", class: "fas fa-gift" },
    { name: "Truck", class: "fas fa-truck" },
    { name: "Box Open", class: "fas fa-box-open" },
    { name: "Receipt", class: "fas fa-receipt" },
    { name: "Cash Register", class: "fas fa-cash-register" },
    { name: "Percentage", class: "fas fa-percentage" },
    { name: "Money Bill Wave", class: "fas fa-money-bill-wave" },
  ],
  "واجهات وبرمجة": [
    { name: "Code Branch", class: "fas fa-code-branch" },
    { name: "File Code", class: "far fa-file-code" },
    { name: "Terminal", class: "fas fa-terminal" },
    { name: "Bug", class: "fas fa-bug" },
    { name: "Database", class: "fas fa-database" },
    { name: "Server", class: "fas fa-server" },
    { name: "Keyboard", class: "far fa-keyboard" },
    { name: "Laptop Code", class: "fas fa-laptop-code" },
    { name: "Mobile Alt", class: "fas fa-mobile-alt" },
    { name: "Window Restore", class: "far fa-window-restore" },
    { name: "Shield Virus", class: "fas fa-shield-virus" },
    { name: "User Secret", class: "fas fa-user-secret" },
    { name: "Filter", class: "fas fa-filter" },
    { name: "Fingerprint", class: "fas fa-fingerprint" },
    { name: "Cloud Upload Alt", class: "fas fa-cloud-upload-alt" },
  ],
  "متنوعة": [
    { name: "Star", class: "far fa-star" },
    { name: "Heart", class: "far fa-heart" },
    { name: "Thumbs Up", class: "far fa-thumbs-up" },
    { name: "Flag", class: "far fa-flag" },
    { name: "Bookmark", class: "far fa-bookmark" },
    { name: "Calendar Alt", class: "far fa-calendar-alt" },
    { name: "Clock", class: "far fa-clock" },
    { name: "Map Marker Alt", class: "fas fa-map-marker-alt" },
    { name: "Link", class: "fas fa-link" },
    { name: "Paperclip", class: "fas fa-paperclip" },
    { name: "Key", class: "fas fa-key" },
    { name: "Trophy", class: "fas fa-trophy" },
    { name: "Graduation Cap", class: "fas fa-graduation-cap" },
    { name: "Book", class: "fas fa-book" },
    { name: "Rocket", class: "fas fa-rocket" },
  ],
};